---
### group_vars/DC1_SPINES.yml

type: l3spine     # Must be either l2spine|l3spine

# Spine Switches
l3spine:
  defaults:
    platform: cEOSLab
    spanning_tree_mode: mstp
    spanning_tree_priority: 4096
    # Loopback is used to generate a router-id
    loopback_ipv4_pool: 192.168.1.0/24
    mlag_peer_ipv4_pool: 192.168.0.0/24
    # Needed for L3 peering across the MLAG Trunk
    mlag_peer_l3_ipv4_pool: 10.1.1.0/24
    # Used for SVI Virtual MAC address
    virtual_router_mac_address: 00:1c:73:00:dc:01
    mlag_interfaces: [Ethernet1, Ethernet2]
  node_groups:
    - group: SPINES
      nodes:
        - name: SPINE_1
          id: 1
          mgmt_ip: 172.100.100.11/24
        - name: SPINE_2
          id: 2
          mgmt_ip: 172.100.100.12/24
