---
### group_vars/DC1_ENDPOINTS.yml
servers:
  - name: Host1
    rack: RACK1
    adapters:
      - endpoint_ports: [Eth1, Eth2]
        switch_ports: [Ethernet5, Ethernet5]
        switches: [LEAF_1A, LEAF_1B]
        vlans: 10
        # L2 mode of the port.
        mode: access
        # Spanning tree portfast configuration on this port.
        spanning_tree_portfast: edge
        # Definition of the pair of ports as port channel.
        port_channel:
          # The port-channel name on the endpoint that will be used in the port-channel description.
          endpoint_port_channel: Bond1
          mode: active
  - name: Host2
    rack: RACK1
    adapters:
      - endpoint_ports: [Eth1, Eth2]
        switch_ports: [Ethernet6, Ethernet6]
        switches: [LEAF_1A, LEAF_1B]
        vlans: 20
        mode: access
        spanning_tree_portfast: edge
        port_channel:
          endpoint_port_channel: Bond1
          mode: active
  - name: Host3
    rack: RACK2
    adapters:
      - endpoint_ports: [Eth1, Eth2]
        switch_ports: [Ethernet5, Ethernet5]
        switches: [LEAF_2A, LEAF_2B]
        vlans: 10
        mode: access
        spanning_tree_portfast: edge
        port_channel:
          endpoint_port_channel: Bond1
          mode: active
  - name: Host4
    rack: RACK2
    adapters:
      - endpoint_ports: [Eth1, Eth2]
        switch_ports: [Ethernet6, Ethernet6]
        switches: [LEAF_2A, LEAF_2B]
        vlans: 30
        mode: access
        spanning_tree_portfast: edge
        port_channel:
          endpoint_port_channel: Bond1
          mode: active
