---
### group_vars/DC1_SPINES.yml

type: spine     # Must be either l2spine|l3spine

# Spine Switches
spine:
  defaults:
    platform: cEOSLab
    # Pool of IPv4 addresses to configure interface Loopback0 used for BGP EVPN sessions
    loopback_ipv4_pool: 10.255.0.0/27
    # Autonous System Number for BGP
    bgp_as: 65100
  nodes:
    - name: SPINE_1
      id: 1
      mgmt_ip: 172.100.100.11/24
    - name: SPINE_2
      id: 2
      mgmt_ip: 172.100.100.12/24
