---
### group_vars/DC1_LEAFS.yml

type: l3leaf

# Leaf Switches
l3leaf:
  defaults:
    platform: cEOSLab
    # Pool of IPv4 addresses to configure interface Loopback0 used for BGP EVPN sessions
    loopback_ipv4_pool: 10.255.0.0/27
    # Offset all assigned loopback IP addresses.
    # Required when the < loopback_ipv4_pool > is same for 2 different node_types (like spine and l3leaf) to avoid over-lapping IPs.
    # For example, set the minimum offset l3leaf.defaults.loopback_ipv4_offset: < total # spine switches > or vice versa.
    loopback_ipv4_offset: 2
    # Definition of pool of IPs to be used as Virtual Tunnel EndPoint (VXLAN origin and destination IPs)
    vtep_loopback_ipv4_pool: 10.255.1.0/27
    # Ansible hostname of the devices used to establish neighborship (IP assignments and BGP peering)
    uplink_switches: [SPINE_1, SPINE_2]
    uplink_interfaces: [Ethernet3, Ethernet4]
    mlag_interfaces: [Ethernet1, Ethernet2]
    # Definition of pool of IPs to be used in P2P links
    uplink_ipv4_pool: 10.255.255.0/26
    # Definition of pool of IPs to be used for MLAG peer-link connectivity
    mlag_peer_ipv4_pool: 10.255.1.64/27
    # iBGP Peering between MLAG peers
    mlag_peer_l3_ipv4_pool: 10.255.1.96/27
    # Virtual router mac for VNIs assigned to Leaf switches in format xx:xx:xx:xx:xx:xx
    virtual_router_mac_address: 00:1c:73:00:00:99
    spanning_tree_priority: 4096
    spanning_tree_mode: mstp

  node_groups:
    - group: RACK1
      # ASN to be used by BGP for the group. Both devices in the MLAG pair will use the same BGP ASN
      bgp_as: 65101
      nodes:
        - name: LEAF_1A
          id: 1
          mgmt_ip: 172.100.100.13/24
        - name: LEAF_1B
          id: 2
          mgmt_ip: 172.100.100.14/24
    - group: RACK2
      bgp_as: 65102
      nodes:
        - name: LEAF_2A
          id: 3
          mgmt_ip: 172.100.100.15/24
        - name: LEAF_2B
          id: 4
          mgmt_ip: 172.100.100.16/24
