---
### group_vars/DC1_SPINES.yml

type: l2spine     # Must be either l2spine|l3spine

# Spine Switches (L2 only)
l2spine:
  defaults:
    platform: cEOSLab
    spanning_tree_mode: mstp
    spanning_tree_priority: 4096
    mlag_peer_ipv4_pool: 192.168.0.0/24
    mlag_interfaces: [Ethernet1, Ethernet2]
  node_groups:
    - group: SPINES
      nodes:
        - name: SPINE1
          id: 1
          mgmt_ip: 172.100.100.11/24
        - name: SPINE2
          id: 2
          mgmt_ip: 172.100.100.12/24
